name: Check
on:
  push:
    branches:
      - main
  pull_request:
    types: [ready_for_review]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest]
        python-version: [ '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: python -c "import sys; print(sys.version)"
      
      # install dependencies
      - uses: actions/checkout
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: pip install -r requirements.txt

      # run main file
      - name: run main script
        run: |
          pipenv shell
          python3 main.py